#! /usr/bin/env bash

## Usage: ./build [--push]

set -euo pipefail

if [[ $# -gt 0 && $1 == "--push" ]]; then
  push=true
else
  push=false
fi

git_sha=$(git rev-parse --short HEAD)

docker buildx build \
  -t saladtechnologies/sdnext:base \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  --build-arg GIT_SHA=$git_sha \
  .

docker tag saladtechnologies/sdnext:base saladtechnologies/sdnext:$git_sha

if [[ $push == true ]]; then
  echo "Pushing saladtechnologies/sdnext:base"
  docker push saladtechnologies/sdnext:base

  echo "Pushing saladtechnologies/sdnext:$git_sha"
  docker push saladtechnologies/sdnext:$git_sha
fi
